application:
  subdomain: backup-x
  background_task: true
  multi_instance: false
  upstreams:
    - location: /
      backend: http://backup-x:9977/
services:
  backup-x:
    # upstream: jeessy/backup-x:v2.9.0
    image: registry.lazycat.cloud/czyt/jeessy/backup-x:e185086ba0329f62
    binds:
      - /lzcapp/var/backup-x-files:/app/backup-x-files
