lzc-sdk-version: "0.1"
name: backup-x
package: cloud.lazycat.app.backup-x
version: 2.8.0
description: 带Web界面的数据库/文件备份增强工具
homepage: https://github.com/jeessy2/backup-x
author: jeessy2
application:
  subdomain: backup-x
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://backup-x.cloud.lazycat.app.backup-x.lzcapp:9977/
services:
  backup-x:
    image: registry.lazycat.cloud/czyt/jeessy/backup-x:ba2531bfd8dbf185
    binds:
      - /lzcapp/var/backup-x-files:/app/backup-x-files
